- name: Install httpd
  yum:
    name: httpd
    state: present
  when: ansible_distribution == "Amazon" or ansible_distribution == "Centos"

- name: start and enable httpd
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "Amazon" or ansible_distribution == "Centos"

- name: Install apache
  apt:
    name: apache2
    state: present
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name: start and enable apache2
  service:
    name: apache2
    state: started
    enabled: yes
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
